engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
exclude_paths:
  - "test/"
  - "client/test"
  - "client/helpers"
  - "client/mocks"