language: node_js
node_js:
 - "node"
 - "8"

env:
 - NODE_ENV=test
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookmeal_test;" -U postgres
  - sequelize "db:migrate"

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
 