language: node_js
node_js:
 - "node"
 - "8"

env:
  global:
    - CC_TEST_REPORTER_ID=60564334cd3bd82dd6bab4944bd1be03c2ce90eb4ade1ee578679ae6a416d759

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookmeals;" -U postgres
  - chmod 0755 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - codeclimate < coverage/lcov.info
 