env:
  global:
    - CC_TEST_REPORTER_ID=60564334cd3bd82dd6bab4944bd1be03c2ce90eb4ade1ee578679ae6a416d759
language: node_js
node_js:
 - "node"
 - "6"
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE mealdb;" -U postgres
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
script:
 - bundle exec rspec
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT