
export const LOAD_ALL_MEALS = 'LOAD_ALL_MEALS';
export const LOAD_MOST_ORDERED = 'LOAD_MOST_ORDERED';
export const LOAD_ERROR_MESSAGE = 'LOAD_ERROR_MESSAGE';
export const LOAD_SUCCESS_MESSAGE = 'LOAD_SUCCESS_MESSAGE';
export const LOAD_TODAY_MENU = 'LOAD_TODAY_MENU';
export const LOAD_MY_ORDER = 'LOAD_MY_ORDER';
export const LOAD_ALL_ORDER = 'LOAD_ALL_ORDER';
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_USER = 'LOAD_USER';
